spring:
  application:
    name: AcerVi Backend
  profiles:
    active: dev # alterar pra test para testar no h2

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
